/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as ExampleChatImport } from './routes/example/chat'
import { Route as DemoTanstackQueryImport } from './routes/demo/tanstack-query'
import { Route as DemoStoreImport } from './routes/demo/store'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthSigninImport } from './routes/_auth/signin'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as AuthConfirmEmailImport } from './routes/_auth/confirm-email'
import { Route as AuthChangePasswordImport } from './routes/_auth/change-password'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account/route'
import { Route as ExampleGuitarsIndexImport } from './routes/example/guitars.index'
import { Route as DashboardAccountIndexImport } from './routes/dashboard/account/index'
import { Route as ExampleGuitarsGuitarIdImport } from './routes/example/guitars.$guitarId'
import { Route as DemoStartServerFuncsImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressImport } from './routes/demo/form.address'
import { Route as DemoEntryTestingImport } from './routes/demo/entry.testing'
import { Route as DashboardAccountSettingsImport } from './routes/dashboard/account/settings'
import { Route as DashboardAccountProfileImport } from './routes/dashboard/account/profile'
import { Route as DashboardAccountBillingsImport } from './routes/dashboard/account/billings'
import { Route as DashboardAccountAppearanceImport } from './routes/dashboard/account/appearance'
import { Route as DashboardAccountSubscriptionRouteImport } from './routes/dashboard/account/subscription/route'
import { Route as DashboardAccountSubscriptionIndexImport } from './routes/dashboard/account/subscription/index'
import { Route as DashboardAccountSubscriptionPaymentRouteImport } from './routes/dashboard/account/subscription/payment/route'
import { Route as DashboardAccountSubscriptionPaymentIndexImport } from './routes/dashboard/account/subscription/payment/index'
import { Route as DashboardAccountSubscriptionPaymentSuccessImport } from './routes/dashboard/account/subscription/payment/success'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const ExampleChatRoute = ExampleChatImport.update({
  id: '/example/chat',
  path: '/example/chat',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const DemoStoreRoute = DemoStoreImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthConfirmEmailRoute = AuthConfirmEmailImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthChangePasswordRoute = AuthChangePasswordImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRouteRoute,
} as any)

const DashboardAccountRouteRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const ExampleGuitarsIndexRoute = ExampleGuitarsIndexImport.update({
  id: '/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAccountIndexRoute = DashboardAccountIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAccountRouteRoute,
} as any)

const ExampleGuitarsGuitarIdRoute = ExampleGuitarsGuitarIdImport.update({
  id: '/example/guitars/$guitarId',
  path: '/example/guitars/$guitarId',
  getParentRoute: () => rootRoute,
} as any)

const DemoStartServerFuncsRoute = DemoStartServerFuncsImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRoute,
} as any)

const DemoStartApiRequestRoute = DemoStartApiRequestImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRoute,
} as any)

const DemoFormSimpleRoute = DemoFormSimpleImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRoute,
} as any)

const DemoFormAddressRoute = DemoFormAddressImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRoute,
} as any)

const DemoEntryTestingRoute = DemoEntryTestingImport.update({
  id: '/demo/entry/testing',
  path: '/demo/entry/testing',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAccountSettingsRoute = DashboardAccountSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAccountRouteRoute,
} as any)

const DashboardAccountProfileRoute = DashboardAccountProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardAccountRouteRoute,
} as any)

const DashboardAccountBillingsRoute = DashboardAccountBillingsImport.update({
  id: '/billings',
  path: '/billings',
  getParentRoute: () => DashboardAccountRouteRoute,
} as any)

const DashboardAccountAppearanceRoute = DashboardAccountAppearanceImport.update(
  {
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardAccountRouteRoute,
  } as any,
)

const DashboardAccountSubscriptionRouteRoute =
  DashboardAccountSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => DashboardAccountRouteRoute,
  } as any)

const DashboardAccountSubscriptionIndexRoute =
  DashboardAccountSubscriptionIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountSubscriptionRouteRoute,
  } as any)

const DashboardAccountSubscriptionPaymentRouteRoute =
  DashboardAccountSubscriptionPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => DashboardAccountSubscriptionRouteRoute,
  } as any)

const DashboardAccountSubscriptionPaymentIndexRoute =
  DashboardAccountSubscriptionPaymentIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountSubscriptionPaymentRouteRoute,
  } as any)

const DashboardAccountSubscriptionPaymentSuccessRoute =
  DashboardAccountSubscriptionPaymentSuccessImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => DashboardAccountSubscriptionPaymentRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_auth/change-password': {
      id: '/_auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthChangePasswordImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/confirm-email': {
      id: '/_auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/example/chat': {
      id: '/example/chat'
      path: '/example/chat'
      fullPath: '/example/chat'
      preLoaderRoute: typeof ExampleChatImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/account/subscription': {
      id: '/dashboard/account/subscription'
      path: '/subscription'
      fullPath: '/dashboard/account/subscription'
      preLoaderRoute: typeof DashboardAccountSubscriptionRouteImport
      parentRoute: typeof DashboardAccountRouteImport
    }
    '/dashboard/account/appearance': {
      id: '/dashboard/account/appearance'
      path: '/appearance'
      fullPath: '/dashboard/account/appearance'
      preLoaderRoute: typeof DashboardAccountAppearanceImport
      parentRoute: typeof DashboardAccountRouteImport
    }
    '/dashboard/account/billings': {
      id: '/dashboard/account/billings'
      path: '/billings'
      fullPath: '/dashboard/account/billings'
      preLoaderRoute: typeof DashboardAccountBillingsImport
      parentRoute: typeof DashboardAccountRouteImport
    }
    '/dashboard/account/profile': {
      id: '/dashboard/account/profile'
      path: '/profile'
      fullPath: '/dashboard/account/profile'
      preLoaderRoute: typeof DashboardAccountProfileImport
      parentRoute: typeof DashboardAccountRouteImport
    }
    '/dashboard/account/settings': {
      id: '/dashboard/account/settings'
      path: '/settings'
      fullPath: '/dashboard/account/settings'
      preLoaderRoute: typeof DashboardAccountSettingsImport
      parentRoute: typeof DashboardAccountRouteImport
    }
    '/demo/entry/testing': {
      id: '/demo/entry/testing'
      path: '/demo/entry/testing'
      fullPath: '/demo/entry/testing'
      preLoaderRoute: typeof DemoEntryTestingImport
      parentRoute: typeof rootRoute
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressImport
      parentRoute: typeof rootRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleImport
      parentRoute: typeof rootRoute
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestImport
      parentRoute: typeof rootRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsImport
      parentRoute: typeof rootRoute
    }
    '/example/guitars/$guitarId': {
      id: '/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof ExampleGuitarsGuitarIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/account/': {
      id: '/dashboard/account/'
      path: '/'
      fullPath: '/dashboard/account/'
      preLoaderRoute: typeof DashboardAccountIndexImport
      parentRoute: typeof DashboardAccountRouteImport
    }
    '/example/guitars/': {
      id: '/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars'
      preLoaderRoute: typeof ExampleGuitarsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/account/subscription/payment': {
      id: '/dashboard/account/subscription/payment'
      path: '/payment'
      fullPath: '/dashboard/account/subscription/payment'
      preLoaderRoute: typeof DashboardAccountSubscriptionPaymentRouteImport
      parentRoute: typeof DashboardAccountSubscriptionRouteImport
    }
    '/dashboard/account/subscription/': {
      id: '/dashboard/account/subscription/'
      path: '/'
      fullPath: '/dashboard/account/subscription/'
      preLoaderRoute: typeof DashboardAccountSubscriptionIndexImport
      parentRoute: typeof DashboardAccountSubscriptionRouteImport
    }
    '/dashboard/account/subscription/payment/success': {
      id: '/dashboard/account/subscription/payment/success'
      path: '/success'
      fullPath: '/dashboard/account/subscription/payment/success'
      preLoaderRoute: typeof DashboardAccountSubscriptionPaymentSuccessImport
      parentRoute: typeof DashboardAccountSubscriptionPaymentRouteImport
    }
    '/dashboard/account/subscription/payment/': {
      id: '/dashboard/account/subscription/payment/'
      path: '/'
      fullPath: '/dashboard/account/subscription/payment/'
      preLoaderRoute: typeof DashboardAccountSubscriptionPaymentIndexImport
      parentRoute: typeof DashboardAccountSubscriptionPaymentRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardAccountSubscriptionPaymentRouteRouteChildren {
  DashboardAccountSubscriptionPaymentSuccessRoute: typeof DashboardAccountSubscriptionPaymentSuccessRoute
  DashboardAccountSubscriptionPaymentIndexRoute: typeof DashboardAccountSubscriptionPaymentIndexRoute
}

const DashboardAccountSubscriptionPaymentRouteRouteChildren: DashboardAccountSubscriptionPaymentRouteRouteChildren =
  {
    DashboardAccountSubscriptionPaymentSuccessRoute:
      DashboardAccountSubscriptionPaymentSuccessRoute,
    DashboardAccountSubscriptionPaymentIndexRoute:
      DashboardAccountSubscriptionPaymentIndexRoute,
  }

const DashboardAccountSubscriptionPaymentRouteRouteWithChildren =
  DashboardAccountSubscriptionPaymentRouteRoute._addFileChildren(
    DashboardAccountSubscriptionPaymentRouteRouteChildren,
  )

interface DashboardAccountSubscriptionRouteRouteChildren {
  DashboardAccountSubscriptionPaymentRouteRoute: typeof DashboardAccountSubscriptionPaymentRouteRouteWithChildren
  DashboardAccountSubscriptionIndexRoute: typeof DashboardAccountSubscriptionIndexRoute
}

const DashboardAccountSubscriptionRouteRouteChildren: DashboardAccountSubscriptionRouteRouteChildren =
  {
    DashboardAccountSubscriptionPaymentRouteRoute:
      DashboardAccountSubscriptionPaymentRouteRouteWithChildren,
    DashboardAccountSubscriptionIndexRoute:
      DashboardAccountSubscriptionIndexRoute,
  }

const DashboardAccountSubscriptionRouteRouteWithChildren =
  DashboardAccountSubscriptionRouteRoute._addFileChildren(
    DashboardAccountSubscriptionRouteRouteChildren,
  )

interface DashboardAccountRouteRouteChildren {
  DashboardAccountSubscriptionRouteRoute: typeof DashboardAccountSubscriptionRouteRouteWithChildren
  DashboardAccountAppearanceRoute: typeof DashboardAccountAppearanceRoute
  DashboardAccountBillingsRoute: typeof DashboardAccountBillingsRoute
  DashboardAccountProfileRoute: typeof DashboardAccountProfileRoute
  DashboardAccountSettingsRoute: typeof DashboardAccountSettingsRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
}

const DashboardAccountRouteRouteChildren: DashboardAccountRouteRouteChildren = {
  DashboardAccountSubscriptionRouteRoute:
    DashboardAccountSubscriptionRouteRouteWithChildren,
  DashboardAccountAppearanceRoute: DashboardAccountAppearanceRoute,
  DashboardAccountBillingsRoute: DashboardAccountBillingsRoute,
  DashboardAccountProfileRoute: DashboardAccountProfileRoute,
  DashboardAccountSettingsRoute: DashboardAccountSettingsRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
}

const DashboardAccountRouteRouteWithChildren =
  DashboardAccountRouteRoute._addFileChildren(
    DashboardAccountRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAccountRouteRoute: typeof DashboardAccountRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRouteRoute: DashboardAccountRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRouteRouteWithChildren
  '/change-password': typeof AuthChangePasswordRoute
  '/confirm-email': typeof AuthConfirmEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/example/chat': typeof ExampleChatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/subscription': typeof DashboardAccountSubscriptionRouteRouteWithChildren
  '/dashboard/account/appearance': typeof DashboardAccountAppearanceRoute
  '/dashboard/account/billings': typeof DashboardAccountBillingsRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/settings': typeof DashboardAccountSettingsRoute
  '/demo/entry/testing': typeof DemoEntryTestingRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/dashboard/account/subscription/payment': typeof DashboardAccountSubscriptionPaymentRouteRouteWithChildren
  '/dashboard/account/subscription/': typeof DashboardAccountSubscriptionIndexRoute
  '/dashboard/account/subscription/payment/success': typeof DashboardAccountSubscriptionPaymentSuccessRoute
  '/dashboard/account/subscription/payment/': typeof DashboardAccountSubscriptionPaymentIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/change-password': typeof AuthChangePasswordRoute
  '/confirm-email': typeof AuthConfirmEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/example/chat': typeof ExampleChatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/account/appearance': typeof DashboardAccountAppearanceRoute
  '/dashboard/account/billings': typeof DashboardAccountBillingsRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/settings': typeof DashboardAccountSettingsRoute
  '/demo/entry/testing': typeof DemoEntryTestingRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/dashboard/account/subscription': typeof DashboardAccountSubscriptionIndexRoute
  '/dashboard/account/subscription/payment/success': typeof DashboardAccountSubscriptionPaymentSuccessRoute
  '/dashboard/account/subscription/payment': typeof DashboardAccountSubscriptionPaymentIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRouteRouteWithChildren
  '/_auth/change-password': typeof AuthChangePasswordRoute
  '/_auth/confirm-email': typeof AuthConfirmEmailRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/example/chat': typeof ExampleChatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/subscription': typeof DashboardAccountSubscriptionRouteRouteWithChildren
  '/dashboard/account/appearance': typeof DashboardAccountAppearanceRoute
  '/dashboard/account/billings': typeof DashboardAccountBillingsRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/settings': typeof DashboardAccountSettingsRoute
  '/demo/entry/testing': typeof DemoEntryTestingRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
  '/dashboard/account/subscription/payment': typeof DashboardAccountSubscriptionPaymentRouteRouteWithChildren
  '/dashboard/account/subscription/': typeof DashboardAccountSubscriptionIndexRoute
  '/dashboard/account/subscription/payment/success': typeof DashboardAccountSubscriptionPaymentSuccessRoute
  '/dashboard/account/subscription/payment/': typeof DashboardAccountSubscriptionPaymentIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/dashboard'
    | '/dashboard/account'
    | '/change-password'
    | '/confirm-email'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/example/chat'
    | '/dashboard/'
    | '/dashboard/account/subscription'
    | '/dashboard/account/appearance'
    | '/dashboard/account/billings'
    | '/dashboard/account/profile'
    | '/dashboard/account/settings'
    | '/demo/entry/testing'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/dashboard/account/'
    | '/example/guitars'
    | '/dashboard/account/subscription/payment'
    | '/dashboard/account/subscription/'
    | '/dashboard/account/subscription/payment/success'
    | '/dashboard/account/subscription/payment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/change-password'
    | '/confirm-email'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/example/chat'
    | '/dashboard'
    | '/dashboard/account/appearance'
    | '/dashboard/account/billings'
    | '/dashboard/account/profile'
    | '/dashboard/account/settings'
    | '/demo/entry/testing'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/dashboard/account'
    | '/example/guitars'
    | '/dashboard/account/subscription'
    | '/dashboard/account/subscription/payment/success'
    | '/dashboard/account/subscription/payment'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/dashboard/account'
    | '/_auth/change-password'
    | '/_auth/confirm-email'
    | '/_auth/forgot-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/example/chat'
    | '/dashboard/'
    | '/dashboard/account/subscription'
    | '/dashboard/account/appearance'
    | '/dashboard/account/billings'
    | '/dashboard/account/profile'
    | '/dashboard/account/settings'
    | '/demo/entry/testing'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/dashboard/account/'
    | '/example/guitars/'
    | '/dashboard/account/subscription/payment'
    | '/dashboard/account/subscription/'
    | '/dashboard/account/subscription/payment/success'
    | '/dashboard/account/subscription/payment/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ExampleChatRoute: typeof ExampleChatRoute
  DemoEntryTestingRoute: typeof DemoEntryTestingRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ExampleGuitarsGuitarIdRoute: typeof ExampleGuitarsGuitarIdRoute
  ExampleGuitarsIndexRoute: typeof ExampleGuitarsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ExampleChatRoute: ExampleChatRoute,
  DemoEntryTestingRoute: DemoEntryTestingRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ExampleGuitarsGuitarIdRoute: ExampleGuitarsGuitarIdRoute,
  ExampleGuitarsIndexRoute: ExampleGuitarsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/dashboard",
        "/demo/store",
        "/demo/tanstack-query",
        "/example/chat",
        "/demo/entry/testing",
        "/demo/form/address",
        "/demo/form/simple",
        "/demo/start/api-request",
        "/demo/start/server-funcs",
        "/example/guitars/$guitarId",
        "/example/guitars/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/change-password",
        "/_auth/confirm-email",
        "/_auth/forgot-password",
        "/_auth/signin",
        "/_auth/signup"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/account",
        "/dashboard/"
      ]
    },
    "/dashboard/account": {
      "filePath": "dashboard/account/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/account/subscription",
        "/dashboard/account/appearance",
        "/dashboard/account/billings",
        "/dashboard/account/profile",
        "/dashboard/account/settings",
        "/dashboard/account/"
      ]
    },
    "/_auth/change-password": {
      "filePath": "_auth/change-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/confirm-email": {
      "filePath": "_auth/confirm-email.tsx",
      "parent": "/_auth"
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/signin": {
      "filePath": "_auth/signin.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/demo/store": {
      "filePath": "demo/store.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo/tanstack-query.tsx"
    },
    "/example/chat": {
      "filePath": "example/chat.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/account/subscription": {
      "filePath": "dashboard/account/subscription/route.tsx",
      "parent": "/dashboard/account",
      "children": [
        "/dashboard/account/subscription/payment",
        "/dashboard/account/subscription/"
      ]
    },
    "/dashboard/account/appearance": {
      "filePath": "dashboard/account/appearance.tsx",
      "parent": "/dashboard/account"
    },
    "/dashboard/account/billings": {
      "filePath": "dashboard/account/billings.tsx",
      "parent": "/dashboard/account"
    },
    "/dashboard/account/profile": {
      "filePath": "dashboard/account/profile.tsx",
      "parent": "/dashboard/account"
    },
    "/dashboard/account/settings": {
      "filePath": "dashboard/account/settings.tsx",
      "parent": "/dashboard/account"
    },
    "/demo/entry/testing": {
      "filePath": "demo/entry.testing.tsx"
    },
    "/demo/form/address": {
      "filePath": "demo/form.address.tsx"
    },
    "/demo/form/simple": {
      "filePath": "demo/form.simple.tsx"
    },
    "/demo/start/api-request": {
      "filePath": "demo/start.api-request.tsx"
    },
    "/demo/start/server-funcs": {
      "filePath": "demo/start.server-funcs.tsx"
    },
    "/example/guitars/$guitarId": {
      "filePath": "example/guitars.$guitarId.tsx"
    },
    "/dashboard/account/": {
      "filePath": "dashboard/account/index.tsx",
      "parent": "/dashboard/account"
    },
    "/example/guitars/": {
      "filePath": "example/guitars.index.tsx"
    },
    "/dashboard/account/subscription/payment": {
      "filePath": "dashboard/account/subscription/payment/route.tsx",
      "parent": "/dashboard/account/subscription",
      "children": [
        "/dashboard/account/subscription/payment/success",
        "/dashboard/account/subscription/payment/"
      ]
    },
    "/dashboard/account/subscription/": {
      "filePath": "dashboard/account/subscription/index.tsx",
      "parent": "/dashboard/account/subscription"
    },
    "/dashboard/account/subscription/payment/success": {
      "filePath": "dashboard/account/subscription/payment/success.tsx",
      "parent": "/dashboard/account/subscription/payment"
    },
    "/dashboard/account/subscription/payment/": {
      "filePath": "dashboard/account/subscription/payment/index.tsx",
      "parent": "/dashboard/account/subscription/payment"
    }
  }
}
ROUTE_MANIFEST_END */
